const cardImages = {
  the_fool: require('../assets/cards/the_fool.webp'),
  the_magician: require('../assets/cards/the_magician.webp'),
  the_high_priestess: require('../assets/cards/the_high_priestess.webp'),
  the_empress: require('../assets/cards/the_empress.webp'),
  the_emperor: require('../assets/cards/the_emperor.webp'),
  the_hierophant: require('../assets/cards/the_hierophant.webp'),
  the_lovers: require('../assets/cards/the_lovers.webp'),
  the_chariot: require('../assets/cards/the_chariot.webp'),
  strength: require('../assets/cards/strength.webp'),
  the_hermit: require('../assets/cards/the_hermit.webp'),
  wheel_of_fortune: require('../assets/cards/wheel_of_fortune.webp'),
  justice: require('../assets/cards/justice.webp'),
  the_hanged_man: require('../assets/cards/the_hanged_man.webp'),
  death: require('../assets/cards/death.webp'),
  temperance: require('../assets/cards/temperance.webp'),
  the_devil: require('../assets/cards/the_devil.webp'),
  the_tower: require('../assets/cards/the_tower.webp'),
  the_star: require('../assets/cards/the_star.webp'),
  the_moon: require('../assets/cards/the_moon.webp'),
  the_sun: require('../assets/cards/the_sun.webp'),
  judgement: require('../assets/cards/judgement.webp'),
  the_world: require('../assets/cards/the_world.webp'),
  ace_of_wands: require('../assets/cards/ace_of_wands.webp'),
  two_of_wands: require('../assets/cards/two_of_wands.webp'),
  three_of_wands: require('../assets/cards/three_of_wands.webp'),
  four_of_wands: require('../assets/cards/four_of_wands.webp'),
  five_of_wands: require('../assets/cards/five_of_wands.webp'),
  six_of_wands: require('../assets/cards/six_of_wands.webp'),
  seven_of_wands: require('../assets/cards/seven_of_wands.webp'),
  eight_of_wands: require('../assets/cards/eight_of_wands.webp'),
  nine_of_wands: require('../assets/cards/nine_of_wands.webp'),
  ten_of_wands: require('../assets/cards/ten_of_wands.webp'),
  page_of_wands: require('../assets/cards/page_of_wands.webp'),
  knight_of_wands: require('../assets/cards/knight_of_wands.webp'),
  queen_of_wands: require('../assets/cards/queen_of_wands.webp'),
  king_of_wands: require('../assets/cards/king_of_wands.webp'),
  ace_of_cups: require('../assets/cards/ace_of_cups.webp'),
  two_of_cups: require('../assets/cards/two_of_cups.webp'),
  three_of_cups: require('../assets/cards/three_of_cups.webp'),
  four_of_cups: require('../assets/cards/four_of_cups.webp'),
  five_of_cups: require('../assets/cards/five_of_cups.webp'),
  six_of_cups: require('../assets/cards/six_of_cups.webp'),
  seven_of_cups: require('../assets/cards/seven_of_cups.webp'),
  eight_of_cups: require('../assets/cards/eight_of_cups.webp'),
  nine_of_cups: require('../assets/cards/nine_of_cups.webp'),
  ten_of_cups: require('../assets/cards/ten_of_cups.webp'),
  page_of_cups: require('../assets/cards/page_of_cups.webp'),
  knight_of_cups: require('../assets/cards/knight_of_cups.webp'),
  queen_of_cups: require('../assets/cards/queen_of_cups.webp'),
  king_of_cups: require('../assets/cards/king_of_cups.webp'),
  ace_of_swords: require('../assets/cards/ace_of_swords.webp'),
  two_of_swords: require('../assets/cards/two_of_swords.webp'),
  three_of_swords: require('../assets/cards/three_of_swords.webp'),
  four_of_swords: require('../assets/cards/four_of_swords.webp'),
  five_of_swords: require('../assets/cards/five_of_swords.webp'),
  six_of_swords: require('../assets/cards/six_of_swords.webp'),
  seven_of_swords: require('../assets/cards/seven_of_swords.webp'),
  eight_of_swords: require('../assets/cards/eight_of_swords.webp'),
  nine_of_swords: require('../assets/cards/nine_of_swords.webp'),
  ten_of_swords: require('../assets/cards/ten_of_swords.webp'),
  page_of_swords: require('../assets/cards/page_of_swords.webp'),
  knight_of_swords: require('../assets/cards/knight_of_swords.webp'),
  queen_of_swords: require('../assets/cards/queen_of_swords.webp'),
  king_of_swords: require('../assets/cards/king_of_swords.webp'),
  ace_of_pentacles: require('../assets/cards/ace_of_pentacles.webp'),
  two_of_pentacles: require('../assets/cards/two_of_pentacles.webp'),
  three_of_pentacles: require('../assets/cards/three_of_pentacles.webp'),
  four_of_pentacles: require('../assets/cards/four_of_pentacles.webp'),
  five_of_pentacles: require('../assets/cards/five_of_pentacles.webp'),
  six_of_pentacles: require('../assets/cards/six_of_pentacles.webp'),
  seven_of_pentacles: require('../assets/cards/seven_of_pentacles.webp'),
  eight_of_pentacles: require('../assets/cards/eight_of_pentacles.webp'),
  nine_of_pentacles: require('../assets/cards/nine_of_pentacles.webp'),
  ten_of_pentacles: require('../assets/cards/ten_of_pentacles.webp'),
  page_of_pentacles: require('../assets/cards/page_of_pentacles.webp'),
  knight_of_pentacles: require('../assets/cards/knight_of_pentacles.webp'),
  queen_of_pentacles: require('../assets/cards/queen_of_pentacles.webp'),
  king_of_pentacles: require('../assets/cards/king_of_pentacles.webp'),
  master_card: require('../assets/cards/master_card.webp'),
};

const toSnakeCase = (str) => {
  // ✅ guard: uvek pretvori u string
  if (typeof str !== 'string') str = str?.key ?? str?.label ?? str?.name ?? '';
  str = String(str ?? '');

  return str.replace(/([A-Z])/g, '_$1').toLowerCase();
};

export const getCardImagePath = (key) => {
  if (key == null) return require('../assets/cards/back.webp');
  const snakeKey = toSnakeCase(key);
  return cardImages[snakeKey] || require('../assets/cards/back.webp');
};
